language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: rrSwRnsmZy23K0rxOHZc5MPaNYOF+vo2jzCAGwDPjFKtfOFxks4G5s4Jn7BtBx2WmAzK+Djm05DyoUafL60304rcPGDboETqnYboFXaRMIVI93kXyJgfaL/dO74ED36hN1jeack5IkqUv/G5x+BysoFBb7u3GSkUBMc6TOSq495LDXVTer3zpBIKlFq1RNBTrTQgWUfp5YlGuMXl/7KzSbwbEg2kwFPlMLbvEIkULlhFtLTumchmh/SMUyQyNcFCjvUXvJ5bcuk/p7kVDMvlwMSsStLoPxJ0ZMiNJdK5hiBFtiKw3S1HFjoAP1otGxeeqfdKFmjLpsrcf/otLlu+OagQv260mP/9y+Sp0gxE2wi6Ah85wAAVJFKVVP1vLydwc8S7ppAgej2yd52yMZWYog7Rdma5xwJ4PLXiV6CGg2QbXxhX3Rw5vkGC/k0hPgzk67ZB2yoRS4f81QT4+FG73Mvf9uruTGgHpkD0WHGZVqBWfynx4aSDRqNhuR4kFpD4CIuP8kROU/r55Yjb5/nINkmk4ng2DtUoBfq6vobnE/IIHdbyc5Mfc3tFZyGb7KIGUIu1BRUgBA+Vkc/LL4qN3HXtOHBEnpXWGst7LJ3lYXKmhZF6bFb7j3WItYL5lnWaot6iVIyckOfdTNcYk5w4Vut/4oMrUmTOVveH63/HN3Y=
  file:
    - "mdast-comment-marker.js"
    - "mdast-comment-marker.min.js"
  on:
    tags: true
